### ISSUE TITLE
Task creates Atom.app, should it be Electron.app?

### ISSUE THREAD

**Issue by martinchooooooo** [atom/grunt-download-electron#30]
I'm trying to migrate the build scripts for LightTable which is broken since the name change to Electron. In trying to be consistent and remove the mention of Atom everywhere, I notice that this task creates an Atom.app package. I was expecting an Electron.app directory...

I tried recreating this in a new project buy following the same steps LightTable does, and I get ./electron/Atom.app 

Gruntfile.js
```
module.exports = function(grunt) {

  // Project configuration.
  grunt.initConfig({
    pkg: grunt.file.readJSON('package.json'),
    "download-electron": {
      version: "0.22.1",
      outputDir: "./electron",
      rebuild: true
    }
  });

  grunt.loadNpmTasks('grunt-download-electron');

};
```

package.json
```
{
    "name": "martin",
        "version": "0.1.0",
        "devDependencies": {
            "grunt": "^0.4.5",
            "grunt-download-electron": "^2.0.0"
        }
}
```

Then I run 
```
> npm install grunt-cli
> npm install
> ./node_modules/.bin/grunt download-electron
```

I'm running on 
OSX 10.9,5

**Comment by simtel12** [comment]
This is because the older releases of electron are still all named Atom.  They would all have to be rebuilt in order to rename them, so I suspect they're just going to leave the older releases as atom, and newer ones will be electron.

In order to see Electron.app, upgrade the version that you're downloading to 0.24.0

**Comment by martinchooooooo** [comment]
Ahh perfect, makes sense. 

Cheers for the explanation :-)
